=== Albamunru/LMSGI-2122/B1/T2/ejemplos/XSD/basicos/1.nota/nota.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">
  <xs:element name="note">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="to" type="xs:string"/>
        <xs:element name="from" type="xs:string"/>
        <xs:element name="heading" type="xs:string"/>
        <xs:element name="body" type="xs:string"/>

        <xs:element name="direcciones" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="address" minOccurs="1" maxOccurs="3">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="origen" type="xs:string"/>
                    <xs:element name="destino" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="calle" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Albamunru/LMSGI-2122/B1/T2/ejemplos/XSD/basicos/1.nota/nota.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<note xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./nota.xsd">
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Dont forget me this weekend</body>
  <direcciones>
    <address>
      <origen></origen>
      <destino></destino>
    </address>
    <address calle="orion">
      <origen></origen>
      <destino></destino>
    </address>
    <address calle="orion">
      <origen></origen>
      <destino></destino>
    </address>
  </direcciones>
</note>
